const products = [
    {
        id: 0,
        name: "Space War",
        tag: "spacewar",
        price: 21.99,
        console: "Playstation",
        genre: "Strategy",
        inCart: 0,
        description: "Fight to keep the Zoidbergens from occupying and taking over your home planet Ezu. Fight alongside your friends in this multiplayer game from Fubisoft Corportions.",
        imgSrc: "/images/spacewar.jpg",
    },
    {
        id: 1,
        name: "Assasin",
        tag: "assassin",
        price: 18.99,
        console: "Playstation",
        genre: "First Person Shooter",
        inCart: 0,
        description: "Apply stealth and knowledge to fulfill your missions",
        imgSrc: "../images/assassin.jpg",
    },
    {
        id: 2,
        name: "Black",
        tag: "black",
        price: 21.99,
        console: "Xbox",
        genre: "Strategy",
        inCart: 0,
        description: "You are Bruce Black, the ultimate fighter in this strategy game",
        imgSrc: "/images/black.jpg",
    },
    {
        id: 3,
        name: "Boxer",
        tag: "boxer",
        price: 20.99,
        console: "Xbox",
        genre: "Fighting",
        inCart: 0,
        description: "Fight as any of the worlds most renowned boxers in this remake of the 2002 game",
        imgSrc: "/images/boxer.jpg",
    },
    {
        id: 4,
        name: "Cyberpunk",
        tag: "cyberpunk",
        price: 23.99,
        console: "Xbox/Playstation",
        genre: "Fantasy",
        inCart: 0,
        description: "Explore the world in this futuristic game",
        imgSrc: "/images/cyberpunk.jpg",
    },
    {
        id: 5,
        name: "Forge Legend",
        tag: "forgelegend",
        price: 21.99,
        console: "Xbox",
        genre: "Fantasy",
        inCart: 0,
        description: "Enjoy an age of simpler times, where magic was the way of life",
        imgSrc: "/images/forgelegend.jpg",
    },
    {
        id: 6,
        name: "Ping Pong",
        tag: "pingpong",
        price: 15.49,
        console: "Playstation",
        genre: "Sport",
        inCart: 0,
        description: "play Ping Pong with your friends, either online or in person!",
        imgSrc: "/images/pingpong.jpg",
    },
    {
        id: 7,
        name: "Racing",
        tag: "racing",
        price: 21.99,
        console: "Xbox",
        genre: "Sport",
        inCart: 0,
        description: "Race in the streets of Seoul and many other cities.",
        imgSrc: "/images/racing.jpg",
    },

    {
        id: 8,
        name: "Super Duper",
        tag: "superduper",
        price: 18.99,
        console: "Playstation",
        genre: "Fantasy",
        inCart: 0,
        description: "Evolve your character through different tasks until you become Super Duper!",
        imgSrc: "/images/superduper.jpg",
    },
]